services:

  mysql:
    image: mysql:8.0
    container_name: sucargo-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Sucargo

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./V1__nucleo_sucargo.sql:/docker-entrypoint-initdb.d/V1__nucleo_sucargo.sql:ro

volumes:
  mysql_data: